# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wasin's Dashboard
title_part1: Wasin
title_part2: "'s Dashboard"
email: haxpor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I blog about projects I'm working on. Mostly about mobile games, tech, web service, little tiny things I built for myself or for public, and tech/game industry-wide. Currently I'm living in Shenzhen, China. I'm running a small creative company with my girlfriend here.
baseurl: "/dashboard" # the subpath of your site, e.g. /blog
url: "http://dashboard.wasin.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: haxpor
github_username:  haxpor
instagram_username: haxpor

# Build settings
markdown: redcarpet

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
